minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
pnpm:
  executionEnv:
    nodeVersion: ""
  onlyBuiltDependencies:
    - esbuild
    - sharp
