name: Auto Fill Date in Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update 'updated' date in pushed markdown files
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          FILES=$(git diff --name-only HEAD^ HEAD | grep '\.md$')
          if [ -z "$FILES" ]; then
            echo "No markdown files to update."
          else
            for FILE in $FILES; do
              awk '/^---$/{flag++} flag==1 {print} /^---$/{flag++}' $FILE | sed "/^updated:.*$/s//updated: $DATE/" > temp.md
              sed '1,/---/!b;//{//!d;};r temp.md' $FILE > temp2.md && mv temp2.md $FILE
              rm temp.md
            done
            echo "$FILES" | xargs git add
            git commit -m "Automatically update 'updated' date in markdown files"
            git push
          fi