name: Auto Fill Date in Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update 'published' and 'updated' date in markdown files
        run: |
          DATE=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Current date: $DATE"

          FILES=$(git diff --name-only HEAD HEAD~1 | grep '\.md$')
          echo "Files to update: $FILES"

          if [ -z "$FILES" ]; then
            echo "No markdown files to update."
          else
            for FILE in $FILES; do
              if ! grep -q '^published: [^ ]' $FILE; then
                sed -i "/^published:.*$/s//published: $DATE/" $FILE
              fi
              sed -i "/^updated:.*$/s//updated: $DATE/" $FILE
              cat $FILE
              git add $FILE
            done
            git commit -m "Automatically update 'published' and 'updated' date in markdown files"
            git push
          fi