name: Update README

on:
  push:
    paths:
      - 'LearningNotes/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update README
      run: |
        # Backup the README.md excluding the Updates section
        awk '/## Updates/{exit} {print}' README.md > README.tmp

        # Append the Updates Header
        echo "" >> README.tmp
        echo "## Updates /n" >> README.tmp

        # Append the list of learning note to the Updates section
        for file in LearningNotes/*.md; do
            if [[ -f "$file" ]]; then
            echo "- [$(basename "$file" .md)]($file)" >> README.tmp
            fi
        done


        echo "" >> README.tmp
        echo "## Contact" >> README.tmp

        # Append the rest of the README.md after Updates section if it exists
        awk '/## Contact/ {f=1; next} f' README.md >> README.tmp || true

        # Replace the old README with the new one
        mv README.tmp README.md

    - name: Commit and push if changed
      run: |
        git diff
        if git diff --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with links to LearningNotes"
        git push